In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pickle


In [5]:

with open('x_train_smote.pkl', 'rb') as f:
    x_train_smote = pickle.load(f)

with open('y_train_smote.pkl', 'rb') as f:
    y_train_smote = pickle.load(f)

with open('x_test_scaled.pkl', 'rb') as f:
    x_test_scaled = pickle.load(f)

with open('y_test_encoded.pkl','rb') as f:
    y_test_encoded = pickle.load(f)

print("Files loaded ")

Files loaded 


In [6]:
y_test_encoded.shape

(29178,)

# Model Building

**Random forest**

In [7]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score


rfc_model = RandomForestClassifier( n_estimators=100, n_jobs=-1,random_state=42 )
rfc_model.fit(x_train_smote, y_train_smote)
rfc_predictions = rfc_model.predict(x_test_scaled)


In [8]:
rf_accuracy = accuracy_score(y_test_encoded, rfc_predictions)
rf_Precision = precision_score(y_test_encoded, rfc_predictions, average='weighted')
rf_Recall = recall_score(y_test_encoded, rfc_predictions, average='weighted')
rf_F1_Score = f1_score(y_test_encoded, rfc_predictions, average='weighted')


print(f"rf_accuracy: {rf_accuracy:.2f}")
print(f"rf_Precision: {rf_Precision:.2f}")
print(f"rf_Recall: {rf_Recall:.2f}")
print(f"rf_F1_Score: {rf_F1_Score:.2f}")

from sklearn.metrics import confusion_matrix
print('\n',confusion_matrix(y_test_encoded, rfc_predictions))


rf_accuracy: 0.96
rf_Precision: 0.96
rf_Recall: 0.96
rf_F1_Score: 0.96

 [[  573     0     4     0    28     9     0]
 [    0   409     9     0     0    14     0]
 [    3     9   366     0     1    53     0]
 [    2     0     0   423     0     0     7]
 [   73     0    15     5 19986     9   526]
 [    3    14    36     0     1   378     0]
 [   18     0     3    38   371     0  5792]]


**DecisionTreeClassifier**

In [6]:
from sklearn.tree import DecisionTreeClassifier
Dtc_model=DecisionTreeClassifier(max_depth=4)
Dtc_model.fit(x_train_smote, y_train_smote)
Dtc_prediction = Dtc_model.predict(x_test_scaled)
print('model trained')

model trained


In [7]:
dtc_accuracy = accuracy_score(y_test_encoded, Dtc_prediction)
dtc_Precision = precision_score(y_test_encoded, Dtc_prediction, average='weighted')
dtc_Recall = recall_score(y_test_encoded, Dtc_prediction, average='weighted')
dtc_F1_Score = f1_score(y_test_encoded, Dtc_prediction, average='weighted')


print(f"dtc_accuracy: {dtc_accuracy:.2f}")
print(f"dtc_Precision: {dtc_Precision:.2f}")
print(f"dtc_Recall: {dtc_Recall:.2f}")
print(f"dtc_F1_Score: {dtc_F1_Score:.2f}")

from sklearn.metrics import confusion_matrix
print('\n confusion matrix \n',confusion_matrix(y_test_encoded, rfc_predictions))


dtc_accuracy: 0.64
dtc_Precision: 0.75
dtc_Recall: 0.64
dtc_F1_Score: 0.68

 confusion matrix 
 [[  573     0     4     0    28     9     0]
 [    0   409     9     0     0    14     0]
 [    3     9   366     0     1    53     0]
 [    2     0     0   423     0     0     7]
 [   73     0    15     5 19986     9   526]
 [    3    14    36     0     1   378     0]
 [   18     0     3    38   371     0  5792]]


**logistic regression**

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

lr_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

lr_model.fit(x_train_smote, y_train_smote)
lr_predictions = lr_model.predict(x_test_scaled)
print('model trained')

model trained


In [9]:
from sklearn.metrics import accuracy_score, classification_report
print(f"Accuracy: {accuracy_score(y_test_encoded, lr_predictions)}")
print('\n',classification_report(y_test_encoded, lr_predictions))


Accuracy: 0.6827404208650353

               precision    recall  f1-score   support

           0       0.13      0.76      0.22       614
           1       0.88      0.91      0.89       432
           2       0.63      0.66      0.65       432
           3       0.76      0.97      0.85       432
           4       0.89      0.68      0.77     20614
           5       0.65      0.67      0.66       432
           6       0.52      0.67      0.58      6222

    accuracy                           0.68     29178
   macro avg       0.64      0.76      0.66     29178
weighted avg       0.78      0.68      0.72     29178



In [10]:
lr_accuracy = accuracy_score(y_test_encoded, lr_predictions)
lr_Precision = precision_score(y_test_encoded, lr_predictions, average='weighted')
lr_Recall = recall_score(y_test_encoded, lr_predictions, average='weighted')
lr_F1_Score = f1_score(y_test_encoded, lr_predictions, average='weighted')


print(f"lr_accuracy: {lr_accuracy:.2f}")
print(f"lr_Precision: {lr_Precision:.2f}")
print(f"lr_Recall: {lr_Recall:.2f}")
print(f"lr_F1_Score: {lr_F1_Score:.2f}")

lr_accuracy: 0.68
lr_Precision: 0.78
lr_Recall: 0.68
lr_F1_Score: 0.72


**XG Boost**

In [11]:
import xgboost as xgb
xgb_model = xgb.XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=5,
    random_state=42)

xgb_model.fit(x_train_smote, y_train_smote)

xgb_predictions = xgb_model.predict(x_test_scaled)
print('model trained')

model trained


In [12]:
xgb_accuracy = accuracy_score(y_test_encoded, xgb_predictions)
xgb_Precision = precision_score(y_test_encoded, xgb_predictions,average='weighted')
xgb_Recall = recall_score(y_test_encoded, xgb_predictions, average='weighted')
xgb_F1_Score = f1_score(y_test_encoded, xgb_predictions, average='weighted')


print(f"xgb_accuracy: {xgb_accuracy:.2f}")
print(f"xgb_Precision: {xgb_Precision:.2f}")
print(f"xgb_Recall: {xgb_Recall:.2f}")
print(f"xgb_F1_Score: {xgb_F1_Score:.2f}")

xgb_accuracy: 0.84
xgb_Precision: 0.87
xgb_Recall: 0.84
xgb_F1_Score: 0.85


**KNN**

In [13]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
knn.fit(x_train_smote, y_train_smote)
knn_predictions = knn.predict(x_test_scaled)
print('model trained')

model trained


In [14]:
knn_accuracy = accuracy_score(y_test_encoded, knn_predictions)
knn_Precision = precision_score(y_test_encoded, knn_predictions,average='weighted')
knn_Recall = recall_score(y_test_encoded, knn_predictions, average='weighted')
knn_F1_Score = f1_score(y_test_encoded, knn_predictions, average='weighted')


print(f"knn_accuracy: {knn_accuracy:.2f}")
print(f"knn_Precision: {knn_Precision:.2f}")
print(f"knn_Recall: {knn_Recall:.2f}")
print(f"knn_F1_Score: {knn_F1_Score:.2f}")

knn_accuracy: 0.89
knn_Precision: 0.91
knn_Recall: 0.89
knn_F1_Score: 0.90


**checking fianl score**

In [15]:

results = pd.DataFrame({
    "Model": [
        "Random Forest",
        "Decision Tree",
        "Logistic Regression",
        "XGBoost",
        "KNN"
    ],
    "Accuracy": [
        rf_accuracy,
        dtc_accuracy,
        lr_accuracy,
        xgb_accuracy,
        knn_accuracy
    ],
    "F1": [
        rf_F1_Score,
        dtc_F1_Score,
        lr_F1_Score,
        xgb_F1_Score,
        knn_F1_Score
    ]
})

print(results.sort_values("F1", ascending=False))

                 Model  Accuracy        F1
0        Random Forest  0.957125  0.957390
4                  KNN  0.893756  0.897638
3              XGBoost  0.844129  0.851630
2  Logistic Regression  0.682740  0.716268
1        Decision Tree  0.641031  0.679719


In [9]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(
    y_test_encoded,
    rfc_predictions
)

print(cm)

[[  573     0     4     0    28     9     0]
 [    0   409     9     0     0    14     0]
 [    3     9   366     0     1    53     0]
 [    2     0     0   423     0     0     7]
 [   73     0    15     5 19986     9   526]
 [    3    14    36     0     1   378     0]
 [   18     0     3    38   371     0  5792]]


In [10]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(
    rfc_model,
    x_train_smote,
    y_train_smote,
    cv=5,
    scoring='f1_weighted'
)

print(scores)
print(scores.mean())

[0.99035594 0.99126025 0.99284005 0.99270071 0.99303028]
0.9920374448127773


**train vs test accuracy**

In [ ]:
train_pred = rfc_model.predict(x_train_smote)
print(
    "Train Accuracy:",
    accuracy_score(y_train_smote, train_pred)
)
print(
    "Test Accuracy:",
    accuracy_score(y_test_encoded, rfc_predictions)
)

In [21]:
import random

for _ in range(10):
    idx = random.randint(0, len(x_test_scaled)-1)

    actual = y_test_encoded.iloc[idx] if hasattr(y_test_encoded, 'iloc') else y_test_encoded[idx]

    pred = rfc_model.predict(
        x_test_scaled.iloc[[idx]] if hasattr(x_test_scaled, 'iloc')
        else x_test_scaled[idx:idx+1]
    )[0]

    print(f"Index: {idx}")
    print(f"Actual: {actual}")
    print(f"Predicted: {pred}")
    print()

Index: 20644
Actual: 4
Predicted: 4

Index: 17467
Actual: 4
Predicted: 4

Index: 18698
Actual: 4
Predicted: 4

Index: 26763
Actual: 4
Predicted: 4

Index: 27515
Actual: 0
Predicted: 0

Index: 7469
Actual: 4
Predicted: 4

Index: 18563
Actual: 4
Predicted: 4

Index: 2629
Actual: 4
Predicted: 4

Index: 15118
Actual: 4
Predicted: 4

Index: 6850
Actual: 4
Predicted: 4



**hyper parameter tuning for best model**

In [19]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier

param_dist = {
    "n_estimators": [100, 200, 300],
    "max_depth": [10, 20, 30, None],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4]
}

rf = RandomForestClassifier(
    random_state=42,
    n_jobs=-1
)

random_search = RandomizedSearchCV(
    rf,
    param_distributions=param_dist,
    n_iter=5,          
    cv=3,
    scoring="f1_weighted",
    n_jobs=-1,
    random_state=42
)

random_search.fit(x_train_smote, y_train_smote)

print(random_search.best_params_)
print(random_search.best_score_)

{'n_estimators': 300, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_depth': None}
0.9913409780879414


In [20]:
best_rf = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    random_state=42,
    n_jobs=-1
)

best_rf.fit(x_train_smote, y_train_smote)

pred = best_rf.predict(x_test_scaled)

print("Accuracy:", accuracy_score(y_test_encoded, pred))
print("F1:", f1_score(y_test_encoded, pred, average='weighted'))

Accuracy: 0.9578106792789087
F1: 0.9580866792103008


**saving best model**

In [21]:
import pickle

with open("random_forest.pkl", "wb") as f:
    pickle.dump(best_rf, f)

print('file loaded')

with open("random_forest.pkl", "rb") as f:
    model = pickle.load(f)
print('done')

file loaded
done
